# Generated by Django 4.2.1 on 2023-05-20 16:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_delete_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('article', models.TextField()),
                ('audio', models.FileField(upload_to='blog/audio/')),
                ('image', models.ImageField(upload_to='blog/images/')),
                ('created', models.DateField(default=datetime.datetime(2023, 5, 20, 16, 36, 21, 143129, tzinfo=datetime.timezone.utc))),
                ('published', models.DateTimeField(blank=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
