# Generated by Django 4.2.1 on 2023-05-20 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 5, 20, 16, 37, 34, 849245, tzinfo=datetime.timezone.utc)),
        ),
    ]
