# Generated by Django 4.2.1 on 2023-05-20 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 5, 20, 18, 16, 8, 768125, tzinfo=datetime.timezone.utc)),
        ),
    ]
