# Generated by Django 4.2.1 on 2023-05-22 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='audio',
            field=models.FileField(blank=True, upload_to='blog/audio/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 5, 22, 11, 55, 53, 635331, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
