# Generated by Django 4.2.1 on 2023-05-22 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_audio_alter_article_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 5, 22, 14, 49, 0, 798066, tzinfo=datetime.timezone.utc)),
        ),
    ]
