# Generated by Django 4.2.1 on 2023-05-22 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 5, 22, 16, 3, 8, 215150, tzinfo=datetime.timezone.utc)),
        ),
    ]
