# Generated by Django 4.2.1 on 2023-05-24 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_article_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 15, 43, 12, 374701, tzinfo=datetime.timezone.utc)),
        ),
    ]
