# Generated by Django 4.2.1 on 2023-06-04 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_article_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 15, 55, 22, 210387, tzinfo=datetime.timezone.utc)),
        ),
    ]
