# Generated by Django 4.2.1 on 2023-06-07 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_article_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 14, 27, 26, 326761, tzinfo=datetime.timezone.utc)),
        ),
    ]
