# Generated by Django 4.2.1 on 2023-06-07 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_article_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 16, 33, 23, 937380, tzinfo=datetime.timezone.utc)),
        ),
    ]
