# Generated by Django 4.2.1 on 2023-06-07 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_article_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 20, 18, 42, 726005, tzinfo=datetime.timezone.utc)),
        ),
    ]
